/**
 * Indian Food Cache Seed Data — v2
 * 140+ common Indian foods with accurate nutritional data per standard serving
 * Sources: IFCT 2017, NIN India, USDA
 * 
 * Covers: Breakfast, Lunch, Dinner, Snacks, Drinks, Sweets, Regional, Supplements
 * Each food has rich aliases covering: Hindi, Hinglish, spelling variants, regional names
 */

/**
 * @param { import("knex").Knex } knex
 */
export async function seed(knex) {
  await knex('indian_food_cache').del();

  const foods = [
    // ━━━━━━━━━━━━━ GRAINS & BREADS ━━━━━━━━━━━━━
    {
      food_name: 'roti', food_name_hi: 'रोटी',
      aliases: JSON.stringify(['chapati', 'chapatti', 'chapathi', 'chappati', 'phulka', 'fulka', 'chapatti', 'चपाती', 'रोटी']),
      default_unit: 'piece', default_quantity: 1,
      calories_per_serving: 104, protein_per_serving: 3.1, carbs_per_serving: 18.3, fat_per_serving: 2.5,
      fibre_per_serving: 2.1, sugar_per_serving: 0.4, sodium_per_serving: 148,
      category: 'grain', is_veg: true, confidence: 0.98,
    },
    {
      food_name: 'rice', food_name_hi: 'चावल',
      aliases: JSON.stringify(['chawal', 'steamed rice', 'white rice', 'plain rice', 'boiled rice', 'chawl', 'चावल', 'भात', 'basmati']),
      default_unit: 'katori', default_quantity: 1,
      calories_per_serving: 180, protein_per_serving: 3.5, carbs_per_serving: 40, fat_per_serving: 0.4,
      fibre_per_serving: 0.6, sugar_per_serving: 0.1, sodium_per_serving: 1,
      category: 'grain', is_veg: true, confidence: 0.97,
    },
    {
      food_name: 'paratha', food_name_hi: 'पराठा',
      aliases: JSON.stringify(['plain paratha', 'parantha', 'prantha', 'parata', 'पराठा', 'परांठा']),
      default_unit: 'piece', default_quantity: 1,
      calories_per_serving: 220, protein_per_serving: 4.2, carbs_per_serving: 28, fat_per_serving: 10,
      fibre_per_serving: 2.0, sugar_per_serving: 0.5, sodium_per_serving: 200,
      category: 'grain', is_veg: true, confidence: 0.97,
    },
    {
      food_name: 'aloo paratha', food_name_hi: 'आलू पराठा',
      aliases: JSON.stringify(['potato paratha', 'alu paratha', 'aloo ka paratha', 'aloo pratha', 'आलू पराठा', 'aaloo paratha']),
      default_unit: 'piece', default_quantity: 1,
      calories_per_serving: 280, protein_per_serving: 5.5, carbs_per_serving: 35, fat_per_serving: 13,
      fibre_per_serving: 2.5, sugar_per_serving: 1.0, sodium_per_serving: 250,
      category: 'grain', is_veg: true, confidence: 0.96,
    },
    {
      food_name: 'gobi paratha', food_name_hi: 'गोभी पराठा',
      aliases: JSON.stringify(['cauliflower paratha', 'gobhi paratha', 'gobi pratha', 'गोभी पराठा']),
      default_unit: 'piece', default_quantity: 1,
      calories_per_serving: 250, protein_per_serving: 5.0, carbs_per_serving: 30, fat_per_serving: 12,
      fibre_per_serving: 2.5, sugar_per_serving: 1.0, sodium_per_serving: 220,
      category: 'grain', is_veg: true, confidence: 0.95,
    },
    {
      food_name: 'paneer paratha', food_name_hi: 'पनीर पराठा',
      aliases: JSON.stringify(['cheese paratha', 'paneer pratha', 'पनीर पराठा']),
      default_unit: 'piece', default_quantity: 1,
      calories_per_serving: 290, protein_per_serving: 10, carbs_per_serving: 28, fat_per_serving: 16,
      fibre_per_serving: 2.0, sugar_per_serving: 1.0, sodium_per_serving: 260,
      category: 'grain', is_veg: true, confidence: 0.95,
    },
    {
      food_name: 'naan', food_name_hi: 'नान',
      aliases: JSON.stringify(['butter naan', 'plain naan', 'tandoori naan', 'nan', 'नान']),
      default_unit: 'piece', default_quantity: 1,
      calories_per_serving: 262, protein_per_serving: 7.6, carbs_per_serving: 43, fat_per_serving: 6.5,
      fibre_per_serving: 1.7, sugar_per_serving: 3.0, sodium_per_serving: 380,
      category: 'grain', is_veg: true, confidence: 0.95,
    },
    {
      food_name: 'poha', food_name_hi: 'पोहा',
      aliases: JSON.stringify(['flattened rice', 'beaten rice', 'chivda', 'aval', 'atukulu', 'पोहा', 'पौआ']),
      default_unit: 'plate', default_quantity: 1,
      calories_per_serving: 250, protein_per_serving: 5.0, carbs_per_serving: 42, fat_per_serving: 7.0,
      fibre_per_serving: 2.0, sugar_per_serving: 1.0, sodium_per_serving: 350,
      category: 'grain', is_veg: true, confidence: 0.96,
    },
    {
      food_name: 'upma', food_name_hi: 'उपमा',
      aliases: JSON.stringify(['suji upma', 'rava upma', 'semolina upma', 'उपमा', 'uppma']),
      default_unit: 'plate', default_quantity: 1,
      calories_per_serving: 230, protein_per_serving: 6.0, carbs_per_serving: 35, fat_per_serving: 8.0,
      fibre_per_serving: 2.5, sugar_per_serving: 1.0, sodium_per_serving: 400,
      category: 'grain', is_veg: true, confidence: 0.95,
    },
    {
      food_name: 'dosa', food_name_hi: 'डोसा',
      aliases: JSON.stringify(['plain dosa', 'sada dosa', 'dose', 'dosha', 'डोसा', 'dosa']),
      default_unit: 'piece', default_quantity: 1,
      calories_per_serving: 168, protein_per_serving: 4.0, carbs_per_serving: 28, fat_per_serving: 4.5,
      fibre_per_serving: 1.5, sugar_per_serving: 0.5, sodium_per_serving: 200,
      category: 'grain', is_veg: true, confidence: 0.97,
    },
    {
      food_name: 'masala dosa', food_name_hi: 'मसाला डोसा',
      aliases: JSON.stringify(['masala dose', 'masala dosha', 'मसाला डोसा']),
      default_unit: 'piece', default_quantity: 1,
      calories_per_serving: 320, protein_per_serving: 6.5, carbs_per_serving: 45, fat_per_serving: 13,
      fibre_per_serving: 3.0, sugar_per_serving: 1.5, sodium_per_serving: 350,
      category: 'grain', is_veg: true, confidence: 0.96,
    },
    {
      food_name: 'uttapam', food_name_hi: 'उत्तपम',
      aliases: JSON.stringify(['uthappam', 'uttappam', 'onion uttapam', 'उत्तपम']),
      default_unit: 'piece', default_quantity: 1,
      calories_per_serving: 200, protein_per_serving: 5.5, carbs_per_serving: 32, fat_per_serving: 6.0,
      fibre_per_serving: 2.0, sugar_per_serving: 2.0, sodium_per_serving: 320,
      category: 'grain', is_veg: true, confidence: 0.95,
    },
    {
      food_name: 'idli', food_name_hi: 'इडली',
      aliases: JSON.stringify(['idly', 'rice idli', 'इडली']),
      default_unit: 'piece', default_quantity: 1,
      calories_per_serving: 58, protein_per_serving: 2.0, carbs_per_serving: 11, fat_per_serving: 0.4,
      fibre_per_serving: 0.8, sugar_per_serving: 0.2, sodium_per_serving: 120,
      category: 'grain', is_veg: true, confidence: 0.98,
    },
    {
      food_name: 'puri', food_name_hi: 'पूरी',
      aliases: JSON.stringify(['poori', 'puri', 'पूरी']),
      default_unit: 'piece', default_quantity: 1,
      calories_per_serving: 120, protein_per_serving: 2.2, carbs_per_serving: 14, fat_per_serving: 6.5,
      fibre_per_serving: 1.0, sugar_per_serving: 0.3, sodium_per_serving: 100,
      category: 'grain', is_veg: true, confidence: 0.97,
    },
    {
      food_name: 'bread', food_name_hi: 'ब्रेड',
      aliases: JSON.stringify(['white bread', 'brown bread', 'toast', 'bread slice', 'ब्रेड', 'डबल रोटी']),
      default_unit: 'slice', default_quantity: 1,
      calories_per_serving: 79, protein_per_serving: 2.7, carbs_per_serving: 14.3, fat_per_serving: 1.0,
      fibre_per_serving: 0.6, sugar_per_serving: 1.5, sodium_per_serving: 150,
      category: 'grain', is_veg: true, confidence: 0.97,
    },
    {
      food_name: 'biryani', food_name_hi: 'बिरयानी',
      aliases: JSON.stringify(['chicken biryani', 'veg biryani', 'dum biryani', 'hyderabadi biryani', 'mutton biryani', 'biryani rice', 'बिरयानी', 'biriyani']),
      default_unit: 'plate', default_quantity: 1,
      calories_per_serving: 490, protein_per_serving: 22, carbs_per_serving: 55, fat_per_serving: 20,
      fibre_per_serving: 2.5, sugar_per_serving: 2.0, sodium_per_serving: 800,
      category: 'grain', is_veg: false, confidence: 0.93,
    },
    {
      food_name: 'oats', food_name_hi: 'ओट्स',
      aliases: JSON.stringify(['oatmeal', 'rolled oats', 'quaker oats', 'ओट्स', 'दलिया']),
      default_unit: 'katori', default_quantity: 1,
      calories_per_serving: 150, protein_per_serving: 5.3, carbs_per_serving: 27, fat_per_serving: 2.5,
      fibre_per_serving: 4.0, sugar_per_serving: 1.0, sodium_per_serving: 2,
      category: 'grain', is_veg: true, confidence: 0.96,
    },
    {
      food_name: 'daliya', food_name_hi: 'दलिया',
      aliases: JSON.stringify(['broken wheat porridge', 'gehun daliya', 'wheat daliya', 'दलिया']),
      default_unit: 'katori', default_quantity: 1,
      calories_per_serving: 170, protein_per_serving: 6.0, carbs_per_serving: 32, fat_per_serving: 1.5,
      fibre_per_serving: 4.5, sugar_per_serving: 0.5, sodium_per_serving: 5,
      category: 'grain', is_veg: true, confidence: 0.95,
    },
    {
      food_name: 'bread omelette', food_name_hi: 'ब्रेड आमलेट',
      aliases: JSON.stringify(['egg bread', 'omelette sandwich', 'egg toast', 'ब्रेड आमलेट']),
      default_unit: 'piece', default_quantity: 1,
      calories_per_serving: 280, protein_per_serving: 14, carbs_per_serving: 22, fat_per_serving: 14,
      fibre_per_serving: 1.0, sugar_per_serving: 2.0, sodium_per_serving: 420,
      category: 'grain', is_veg: false, confidence: 0.94,
    },

    // ━━━━━━━━━━━━━ DAL & LENTILS ━━━━━━━━━━━━━
    {
      food_name: 'dal', food_name_hi: 'दाल',
      aliases: JSON.stringify([
        'daal', 'dhal', 'dal tadka', 'tadka dal', 'yellow dal', 'lentils', 'lentil soup',
        'toor dal', 'tuvar dal', 'arhar dal', 'arhar daal', 'दाल', 'तड़का दाल', 'दाल तड़का',
        'dal fry', 'dal curry', 'plain dal', 'simple dal'
      ]),
      default_unit: 'katori', default_quantity: 1,
      calories_per_serving: 120, protein_per_serving: 7.0, carbs_per_serving: 16, fat_per_serving: 3.5,
      fibre_per_serving: 3.5, sugar_per_serving: 0.8, sodium_per_serving: 300,
      category: 'protein', is_veg: true, confidence: 0.96,
    },
    {
      food_name: 'moong dal', food_name_hi: 'मूंग दाल',
      aliases: JSON.stringify(['mung dal', 'mung bean dal', 'moong daal', 'green moong', 'yellow moong', 'मूंग दाल', 'मूंग']),
      default_unit: 'katori', default_quantity: 1,
      calories_per_serving: 105, protein_per_serving: 7.5, carbs_per_serving: 14, fat_per_serving: 2.5,
      fibre_per_serving: 4.0, sugar_per_serving: 0.5, sodium_per_serving: 280,
      category: 'protein', is_veg: true, confidence: 0.96,
    },
    {
      food_name: 'masoor dal', food_name_hi: 'मसूर दाल',
      aliases: JSON.stringify(['red lentil', 'masoor daal', 'masur dal', 'मसूर दाल', 'red dal']),
      default_unit: 'katori', default_quantity: 1,
      calories_per_serving: 115, protein_per_serving: 8.0, carbs_per_serving: 15, fat_per_serving: 2.0,
      fibre_per_serving: 4.0, sugar_per_serving: 0.5, sodium_per_serving: 260,
      category: 'protein', is_veg: true, confidence: 0.96,
    },
    {
      food_name: 'chana dal', food_name_hi: 'चना दाल',
      aliases: JSON.stringify(['bengal gram dal', 'chana daal', 'चना दाल', 'split chickpea']),
      default_unit: 'katori', default_quantity: 1,
      calories_per_serving: 130, protein_per_serving: 7.5, carbs_per_serving: 17, fat_per_serving: 3.0,
      fibre_per_serving: 4.5, sugar_per_serving: 0.8, sodium_per_serving: 290,
      category: 'protein', is_veg: true, confidence: 0.95,
    },
    {
      food_name: 'dal makhani', food_name_hi: 'दाल मखनी',
      aliases: JSON.stringify(['dal makhni', 'maa ki dal', 'black dal', 'restaurant dal', 'दाल मखनी', 'उरद दाल']),
      default_unit: 'katori', default_quantity: 1,
      calories_per_serving: 210, protein_per_serving: 9.0, carbs_per_serving: 18, fat_per_serving: 12,
      fibre_per_serving: 4.0, sugar_per_serving: 1.5, sodium_per_serving: 500,
      category: 'protein', is_veg: true, confidence: 0.95,
    },
    {
      food_name: 'rajma', food_name_hi: 'राजमा',
      aliases: JSON.stringify(['kidney beans', 'rajma curry', 'rajma masala', 'rajmah', 'राजमा', 'लोबिया']),
      default_unit: 'katori', default_quantity: 1,
      calories_per_serving: 160, protein_per_serving: 9.0, carbs_per_serving: 22, fat_per_serving: 4.0,
      fibre_per_serving: 6.0, sugar_per_serving: 1.0, sodium_per_serving: 400,
      category: 'protein', is_veg: true, confidence: 0.96,
    },
    {
      food_name: 'chole', food_name_hi: 'छोले',
      aliases: JSON.stringify(['chana masala', 'chhole', 'chickpea curry', 'chana', 'छोले', 'चना', 'kabuli chana', 'chole masala']),
      default_unit: 'katori', default_quantity: 1,
      calories_per_serving: 180, protein_per_serving: 8.0, carbs_per_serving: 24, fat_per_serving: 6.0,
      fibre_per_serving: 5.0, sugar_per_serving: 1.5, sodium_per_serving: 450,
      category: 'protein', is_veg: true, confidence: 0.95,
    },
    {
      food_name: 'sambar', food_name_hi: 'सांभर',
      aliases: JSON.stringify(['sambhar', 'sambar curry', 'south indian sambar', 'सांभर', 'sambaram']),
      default_unit: 'katori', default_quantity: 1,
      calories_per_serving: 110, protein_per_serving: 5.5, carbs_per_serving: 15, fat_per_serving: 3.0,
      fibre_per_serving: 3.0, sugar_per_serving: 2.0, sodium_per_serving: 500,
      category: 'protein', is_veg: true, confidence: 0.95,
    },
    {
      food_name: 'khichdi', food_name_hi: 'खिचड़ी',
      aliases: JSON.stringify(['dal khichdi', 'moong khichdi', 'rice khichdi', 'खिचड़ी', 'khichri', 'kitchdi']),
      default_unit: 'katori', default_quantity: 1,
      calories_per_serving: 200, protein_per_serving: 7.0, carbs_per_serving: 30, fat_per_serving: 6.0,
      fibre_per_serving: 3.0, sugar_per_serving: 1.0, sodium_per_serving: 350,
      category: 'grain', is_veg: true, confidence: 0.96,
    },

    // ━━━━━━━━━━━━━ PANEER & DAIRY ━━━━━━━━━━━━━
    {
      food_name: 'paneer', food_name_hi: 'पनीर',
      aliases: JSON.stringify(['cottage cheese', 'paneer tikka', 'raw paneer', 'पनीर']),
      default_unit: 'piece', default_quantity: 100,
      calories_per_serving: 265, protein_per_serving: 18.3, carbs_per_serving: 3.6, fat_per_serving: 20.8,
      fibre_per_serving: 0, sugar_per_serving: 1.2, sodium_per_serving: 22,
      category: 'dairy', is_veg: true, confidence: 0.97,
    },
    {
      food_name: 'paneer butter masala', food_name_hi: 'पनीर बटर मसाला',
      aliases: JSON.stringify(['paneer makhani', 'paneer in gravy', 'butter paneer', 'पनीर बटर मसाला', 'pnr butter masala']),
      default_unit: 'katori', default_quantity: 1,
      calories_per_serving: 320, protein_per_serving: 14, carbs_per_serving: 12, fat_per_serving: 24,
      fibre_per_serving: 2.0, sugar_per_serving: 5.0, sodium_per_serving: 600,
      category: 'dairy', is_veg: true, confidence: 0.94,
    },
    {
      food_name: 'paneer bhurji', food_name_hi: 'पनीर भुर्जी',
      aliases: JSON.stringify(['paneer scramble', 'scrambled paneer', 'भुर्जी', 'पनीर भुर्जी']),
      default_unit: 'katori', default_quantity: 1,
      calories_per_serving: 290, protein_per_serving: 16, carbs_per_serving: 6, fat_per_serving: 23,
      fibre_per_serving: 1.0, sugar_per_serving: 2.0, sodium_per_serving: 350,
      category: 'dairy', is_veg: true, confidence: 0.95,
    },
    {
      food_name: 'curd', food_name_hi: 'दही',
      aliases: JSON.stringify(['dahi', 'yogurt', 'plain curd', 'homemade curd', 'दही', 'doi']),
      default_unit: 'katori', default_quantity: 1,
      calories_per_serving: 98, protein_per_serving: 5.0, carbs_per_serving: 7.0, fat_per_serving: 5.5,
      fibre_per_serving: 0, sugar_per_serving: 7.0, sodium_per_serving: 65,
      category: 'dairy', is_veg: true, confidence: 0.97,
    },
    {
      food_name: 'milk', food_name_hi: 'दूध',
      aliases: JSON.stringify(['dudh', 'full cream milk', 'toned milk', 'cow milk', 'buffalo milk', 'amul milk', 'दूध']),
      default_unit: 'glass', default_quantity: 1,
      calories_per_serving: 150, protein_per_serving: 8.0, carbs_per_serving: 12.0, fat_per_serving: 8.0,
      fibre_per_serving: 0, sugar_per_serving: 12, sodium_per_serving: 100,
      category: 'dairy', is_veg: true, confidence: 0.97,
    },
    {
      food_name: 'lassi', food_name_hi: 'लस्सी',
      aliases: JSON.stringify(['sweet lassi', 'mango lassi', 'punjabi lassi', 'लस्सी', 'dahi lassi']),
      default_unit: 'glass', default_quantity: 1,
      calories_per_serving: 180, protein_per_serving: 6.0, carbs_per_serving: 28, fat_per_serving: 5.0,
      fibre_per_serving: 0, sugar_per_serving: 24, sodium_per_serving: 80,
      category: 'dairy', is_veg: true, confidence: 0.95,
    },
    {
      food_name: 'buttermilk', food_name_hi: 'छाछ',
      aliases: JSON.stringify(['chaas', 'chaach', 'mattha', 'masala chaas', 'छाछ', 'मट्ठा']),
      default_unit: 'glass', default_quantity: 1,
      calories_per_serving: 40, protein_per_serving: 3.0, carbs_per_serving: 5.0, fat_per_serving: 1.0,
      fibre_per_serving: 0, sugar_per_serving: 4.0, sodium_per_serving: 300,
      category: 'dairy', is_veg: true, confidence: 0.96,
    },
    {
      food_name: 'raita', food_name_hi: 'रायता',
      aliases: JSON.stringify(['boondi raita', 'cucumber raita', 'plain raita', 'ryta', 'रायता']),
      default_unit: 'katori', default_quantity: 1,
      calories_per_serving: 75, protein_per_serving: 3.5, carbs_per_serving: 5.0, fat_per_serving: 4.5,
      fibre_per_serving: 0.5, sugar_per_serving: 4.0, sodium_per_serving: 200,
      category: 'dairy', is_veg: true, confidence: 0.95,
    },

    // ━━━━━━━━━━━━━ NON-VEG ━━━━━━━━━━━━━
    {
      food_name: 'egg', food_name_hi: 'अंडा',
      aliases: JSON.stringify(['anda', 'boiled egg', 'scrambled egg', 'omelette', 'omelet', 'egg omelette', 'fried egg', 'अंडा', 'अण्डा']),
      default_unit: 'piece', default_quantity: 1,
      calories_per_serving: 78, protein_per_serving: 6.3, carbs_per_serving: 0.6, fat_per_serving: 5.3,
      fibre_per_serving: 0, sugar_per_serving: 0.6, sodium_per_serving: 62,
      category: 'protein', is_veg: false, confidence: 0.98,
    },
    {
      food_name: 'butter chicken', food_name_hi: 'बटर चिकन',
      aliases: JSON.stringify(['murgh makhani', 'chicken makhani', 'butter murgh', 'बटर चिकन', 'makhani chicken']),
      default_unit: 'katori', default_quantity: 1,
      calories_per_serving: 310, protein_per_serving: 24, carbs_per_serving: 10, fat_per_serving: 20,
      fibre_per_serving: 1.5, sugar_per_serving: 5.0, sodium_per_serving: 650,
      category: 'protein', is_veg: false, confidence: 0.95,
    },
    {
      food_name: 'chicken curry', food_name_hi: 'चिकन करी',
      aliases: JSON.stringify(['chicken gravy', 'murgh', 'chicken sabzi', 'चिकन', 'मुर्ग', 'desi chicken']),
      default_unit: 'katori', default_quantity: 1,
      calories_per_serving: 240, protein_per_serving: 22, carbs_per_serving: 8, fat_per_serving: 14,
      fibre_per_serving: 1.5, sugar_per_serving: 2.0, sodium_per_serving: 550,
      category: 'protein', is_veg: false, confidence: 0.95,
    },
    {
      food_name: 'chicken breast', food_name_hi: 'चिकन ब्रेस्ट',
      aliases: JSON.stringify(['grilled chicken', 'boiled chicken', 'skinless chicken', 'चिकन ब्रेस्ट', 'chicken boneless']),
      default_unit: 'piece', default_quantity: 100,
      calories_per_serving: 165, protein_per_serving: 31, carbs_per_serving: 0, fat_per_serving: 3.6,
      fibre_per_serving: 0, sugar_per_serving: 0, sodium_per_serving: 74,
      category: 'protein', is_veg: false, confidence: 0.97,
    },
    {
      food_name: 'fish curry', food_name_hi: 'मछली करी',
      aliases: JSON.stringify(['machli', 'fish fry', 'fish masala', 'मछली', 'machali curry']),
      default_unit: 'katori', default_quantity: 1,
      calories_per_serving: 200, protein_per_serving: 20, carbs_per_serving: 6, fat_per_serving: 11,
      fibre_per_serving: 1.0, sugar_per_serving: 1.0, sodium_per_serving: 450,
      category: 'protein', is_veg: false, confidence: 0.94,
    },
    {
      food_name: 'mutton curry', food_name_hi: 'मटन करी',
      aliases: JSON.stringify(['goat curry', 'mutton gravy', 'gosht', 'मटन', 'गोश्त', 'lamb curry']),
      default_unit: 'katori', default_quantity: 1,
      calories_per_serving: 310, protein_per_serving: 24, carbs_per_serving: 8, fat_per_serving: 21,
      fibre_per_serving: 1.0, sugar_per_serving: 1.5, sodium_per_serving: 500,
      category: 'protein', is_veg: false, confidence: 0.94,
    },
    {
      food_name: 'tandoori chicken', food_name_hi: 'तंदूरी चिकन',
      aliases: JSON.stringify(['tandoori', 'tandori chicken', 'तंदूरी चिकन', 'tandoor chicken']),
      default_unit: 'piece', default_quantity: 1,
      calories_per_serving: 195, protein_per_serving: 28, carbs_per_serving: 4, fat_per_serving: 8,
      fibre_per_serving: 0.5, sugar_per_serving: 1.0, sodium_per_serving: 550,
      category: 'protein', is_veg: false, confidence: 0.95,
    },
    {
      food_name: 'chicken tikka', food_name_hi: 'चिकन टिक्का',
      aliases: JSON.stringify(['tikka', 'chicken boti', 'चिकन टिक्का', 'grilled tikka']),
      default_unit: 'piece', default_quantity: 3,
      calories_per_serving: 180, protein_per_serving: 25, carbs_per_serving: 4, fat_per_serving: 8,
      fibre_per_serving: 0.5, sugar_per_serving: 1.5, sodium_per_serving: 480,
      category: 'protein', is_veg: false, confidence: 0.95,
    },

    // ━━━━━━━━━━━━━ VEGETABLES & CURRIES ━━━━━━━━━━━━━
    {
      food_name: 'aloo sabzi', food_name_hi: 'आलू सब्जी',
      aliases: JSON.stringify(['potato curry', 'aloo ki sabzi', 'aloo', 'potato sabzi', 'आलू', 'aloo masala', 'dum aloo']),
      default_unit: 'katori', default_quantity: 1,
      calories_per_serving: 160, protein_per_serving: 3.0, carbs_per_serving: 22, fat_per_serving: 7.0,
      fibre_per_serving: 2.5, sugar_per_serving: 2.0, sodium_per_serving: 400,
      category: 'vegetable', is_veg: true, confidence: 0.95,
    },
    {
      food_name: 'palak paneer', food_name_hi: 'पालक पनीर',
      aliases: JSON.stringify(['spinach paneer', 'saag paneer', 'palak curry', 'पालक पनीर', 'पालक']),
      default_unit: 'katori', default_quantity: 1,
      calories_per_serving: 230, protein_per_serving: 12, carbs_per_serving: 8, fat_per_serving: 18,
      fibre_per_serving: 3.0, sugar_per_serving: 2.0, sodium_per_serving: 400,
      category: 'vegetable', is_veg: true, confidence: 0.95,
    },
    {
      food_name: 'mixed sabzi', food_name_hi: 'मिक्स सब्जी',
      aliases: JSON.stringify(['sabzi', 'vegetables', 'subzi', 'mix veg', 'sab', 'सब्जी', 'तरकारी', 'sabji']),
      default_unit: 'katori', default_quantity: 1,
      calories_per_serving: 120, protein_per_serving: 3.5, carbs_per_serving: 12, fat_per_serving: 7.0,
      fibre_per_serving: 3.5, sugar_per_serving: 3.0, sodium_per_serving: 350,
      category: 'vegetable', is_veg: true, confidence: 0.93,
    },
    {
      food_name: 'bhindi', food_name_hi: 'भिंडी',
      aliases: JSON.stringify(['okra', 'ladyfinger', 'bhindi masala', 'bhendi', 'भिंडी', 'ladies finger']),
      default_unit: 'katori', default_quantity: 1,
      calories_per_serving: 110, protein_per_serving: 2.5, carbs_per_serving: 10, fat_per_serving: 7.0,
      fibre_per_serving: 3.0, sugar_per_serving: 1.5, sodium_per_serving: 300,
      category: 'vegetable', is_veg: true, confidence: 0.95,
    },
    {
      food_name: 'gobhi', food_name_hi: 'गोभी',
      aliases: JSON.stringify(['cauliflower', 'aloo gobhi', 'gobi', 'gobhi masala', 'गोभी', 'फूल गोभी', 'flower gobi']),
      default_unit: 'katori', default_quantity: 1,
      calories_per_serving: 130, protein_per_serving: 3.0, carbs_per_serving: 14, fat_per_serving: 7.0,
      fibre_per_serving: 2.5, sugar_per_serving: 2.0, sodium_per_serving: 350,
      category: 'vegetable', is_veg: true, confidence: 0.94,
    },
    {
      food_name: 'matar paneer', food_name_hi: 'मटर पनीर',
      aliases: JSON.stringify(['peas paneer', 'matar panir', 'मटर पनीर', 'peas and cheese curry']),
      default_unit: 'katori', default_quantity: 1,
      calories_per_serving: 260, protein_per_serving: 13, carbs_per_serving: 14, fat_per_serving: 18,
      fibre_per_serving: 3.0, sugar_per_serving: 3.0, sodium_per_serving: 480,
      category: 'vegetable', is_veg: true, confidence: 0.94,
    },
    {
      food_name: 'salad', food_name_hi: 'सलाद',
      aliases: JSON.stringify(['kachumber', 'green salad', 'mix salad', 'vegetable salad', 'सलाद']),
      default_unit: 'plate', default_quantity: 1,
      calories_per_serving: 45, protein_per_serving: 2.0, carbs_per_serving: 8, fat_per_serving: 0.5,
      fibre_per_serving: 3.0, sugar_per_serving: 4.0, sodium_per_serving: 20,
      category: 'vegetable', is_veg: true, confidence: 0.94,
    },

    // ━━━━━━━━━━━━━ BEVERAGES ━━━━━━━━━━━━━
    {
      food_name: 'chai', food_name_hi: 'चाय',
      aliases: JSON.stringify(['tea', 'masala chai', 'cutting chai', 'ginger tea', 'adrak chai', 'indian tea', 'चाय', 'मसाला चाय', 'chai tea']),
      default_unit: 'cup', default_quantity: 1,
      calories_per_serving: 60, protein_per_serving: 2.0, carbs_per_serving: 8, fat_per_serving: 2.0,
      fibre_per_serving: 0, sugar_per_serving: 6.0, sodium_per_serving: 30,
      category: 'beverage', is_veg: true, confidence: 0.97,
    },
    {
      food_name: 'coffee', food_name_hi: 'कॉफी',
      aliases: JSON.stringify(['filter coffee', 'black coffee', 'instant coffee', 'café coffee', 'कॉफी', 'kapi']),
      default_unit: 'cup', default_quantity: 1,
      calories_per_serving: 50, protein_per_serving: 1.5, carbs_per_serving: 6, fat_per_serving: 2.0,
      fibre_per_serving: 0, sugar_per_serving: 5.0, sodium_per_serving: 20,
      category: 'beverage', is_veg: true, confidence: 0.96,
    },
    {
      food_name: 'cold coffee', food_name_hi: 'कोल्ड कॉफी',
      aliases: JSON.stringify(['iced coffee', 'cold brew', 'coffee shake', 'कोल्ड कॉफी', 'cold cafe']),
      default_unit: 'glass', default_quantity: 1,
      calories_per_serving: 180, protein_per_serving: 5.0, carbs_per_serving: 24, fat_per_serving: 7.0,
      fibre_per_serving: 0, sugar_per_serving: 20, sodium_per_serving: 80,
      category: 'beverage', is_veg: true, confidence: 0.94,
    },
    {
      food_name: 'nimbu pani', food_name_hi: 'नींबू पानी',
      aliases: JSON.stringify(['lemon water', 'shikanji', 'lime water', 'lemonade', 'नींबू पानी', 'nimbu juice']),
      default_unit: 'glass', default_quantity: 1,
      calories_per_serving: 45, protein_per_serving: 0.2, carbs_per_serving: 12, fat_per_serving: 0,
      fibre_per_serving: 0, sugar_per_serving: 10, sodium_per_serving: 200,
      category: 'beverage', is_veg: true, confidence: 0.96,
    },
    {
      food_name: 'coconut water', food_name_hi: 'नारियल पानी',
      aliases: JSON.stringify(['nariyal pani', 'coconut juice', 'नारियल पानी', 'naariyal pani']),
      default_unit: 'glass', default_quantity: 1,
      calories_per_serving: 46, protein_per_serving: 1.7, carbs_per_serving: 9, fat_per_serving: 0.5,
      fibre_per_serving: 2.6, sugar_per_serving: 6.0, sodium_per_serving: 252,
      category: 'beverage', is_veg: true, confidence: 0.97,
    },
    {
      food_name: 'sugarcane juice', food_name_hi: 'गन्ने का रस',
      aliases: JSON.stringify(['ganna juice', 'ganne ka ras', 'sugarcane', 'गन्ने का रस', 'गन्ना']),
      default_unit: 'glass', default_quantity: 1,
      calories_per_serving: 180, protein_per_serving: 0.4, carbs_per_serving: 45, fat_per_serving: 0.1,
      fibre_per_serving: 0, sugar_per_serving: 42, sodium_per_serving: 15,
      category: 'beverage', is_veg: true, confidence: 0.96,
    },
    {
      food_name: 'protein shake', food_name_hi: 'प्रोटीन शेक',
      aliases: JSON.stringify(['whey shake', 'protein smoothie', 'protein drink', 'प्रोटीन शेक', 'protein water']),
      default_unit: 'glass', default_quantity: 1,
      calories_per_serving: 180, protein_per_serving: 25, carbs_per_serving: 10, fat_per_serving: 4.0,
      fibre_per_serving: 1.0, sugar_per_serving: 4.0, sodium_per_serving: 150,
      category: 'beverage', is_veg: true, confidence: 0.94,
    },
    {
      food_name: 'orange juice', food_name_hi: 'संतरे का रस',
      aliases: JSON.stringify(['orange juice', 'santra juice', 'mosambi juice', 'citrus juice', 'संतरे का रस']),
      default_unit: 'glass', default_quantity: 1,
      calories_per_serving: 112, protein_per_serving: 1.7, carbs_per_serving: 26, fat_per_serving: 0.5,
      fibre_per_serving: 0.5, sugar_per_serving: 21, sodium_per_serving: 2,
      category: 'beverage', is_veg: true, confidence: 0.95,
    },

    // ━━━━━━━━━━━━━ FRUITS ━━━━━━━━━━━━━
    {
      food_name: 'banana', food_name_hi: 'केला',
      aliases: JSON.stringify(['kela', 'kele', 'केला', 'plantain']),
      default_unit: 'piece', default_quantity: 1,
      calories_per_serving: 105, protein_per_serving: 1.3, carbs_per_serving: 27, fat_per_serving: 0.4,
      fibre_per_serving: 3.1, sugar_per_serving: 14, sodium_per_serving: 1,
      category: 'fruit', is_veg: true, confidence: 0.98,
    },
    {
      food_name: 'apple', food_name_hi: 'सेब',
      aliases: JSON.stringify(['seb', 'सेब', 'red apple', 'green apple']),
      default_unit: 'piece', default_quantity: 1,
      calories_per_serving: 95, protein_per_serving: 0.5, carbs_per_serving: 25, fat_per_serving: 0.3,
      fibre_per_serving: 4.4, sugar_per_serving: 19, sodium_per_serving: 2,
      category: 'fruit', is_veg: true, confidence: 0.98,
    },
    {
      food_name: 'mango', food_name_hi: 'आम',
      aliases: JSON.stringify(['aam', 'alphonso', 'kesar mango', 'आम', 'hapus']),
      default_unit: 'piece', default_quantity: 1,
      calories_per_serving: 150, protein_per_serving: 1.5, carbs_per_serving: 35, fat_per_serving: 0.6,
      fibre_per_serving: 3.0, sugar_per_serving: 31, sodium_per_serving: 3,
      category: 'fruit', is_veg: true, confidence: 0.97,
    },
    {
      food_name: 'papaya', food_name_hi: 'पपीता',
      aliases: JSON.stringify(['papita', 'raw papaya', 'पपीता', 'papeeta']),
      default_unit: 'katori', default_quantity: 1,
      calories_per_serving: 62, protein_per_serving: 0.7, carbs_per_serving: 16, fat_per_serving: 0.4,
      fibre_per_serving: 2.5, sugar_per_serving: 11, sodium_per_serving: 4,
      category: 'fruit', is_veg: true, confidence: 0.97,
    },
    {
      food_name: 'guava', food_name_hi: 'अमरूद',
      aliases: JSON.stringify(['amrood', 'अमरूद', 'peru']),
      default_unit: 'piece', default_quantity: 1,
      calories_per_serving: 68, protein_per_serving: 2.6, carbs_per_serving: 14, fat_per_serving: 1.0,
      fibre_per_serving: 5.4, sugar_per_serving: 9, sodium_per_serving: 2,
      category: 'fruit', is_veg: true, confidence: 0.97,
    },
    {
      food_name: 'watermelon', food_name_hi: 'तरबूज',
      aliases: JSON.stringify(['tarbuj', 'tarbooj', 'तरबूज', 'watermelon slices']),
      default_unit: 'katori', default_quantity: 1,
      calories_per_serving: 46, protein_per_serving: 0.9, carbs_per_serving: 11, fat_per_serving: 0.2,
      fibre_per_serving: 0.6, sugar_per_serving: 9, sodium_per_serving: 2,
      category: 'fruit', is_veg: true, confidence: 0.97,
    },

    // ━━━━━━━━━━━━━ SNACKS & STREET FOOD ━━━━━━━━━━━━━
    {
      food_name: 'samosa', food_name_hi: 'समोसा',
      aliases: JSON.stringify(['samose', 'aloo samosa', 'समोसा', 'singara']),
      default_unit: 'piece', default_quantity: 1,
      calories_per_serving: 252, protein_per_serving: 4.5, carbs_per_serving: 28, fat_per_serving: 14,
      fibre_per_serving: 2.0, sugar_per_serving: 1.0, sodium_per_serving: 350,
      category: 'snack', is_veg: true, confidence: 0.96,
    },
    {
      food_name: 'kachori', food_name_hi: 'कचौरी',
      aliases: JSON.stringify(['kachodi', 'moong kachori', 'dal kachori', 'कचौरी', 'khasta kachori']),
      default_unit: 'piece', default_quantity: 1,
      calories_per_serving: 200, protein_per_serving: 4.0, carbs_per_serving: 22, fat_per_serving: 11,
      fibre_per_serving: 1.5, sugar_per_serving: 0.8, sodium_per_serving: 300,
      category: 'snack', is_veg: true, confidence: 0.95,
    },
    {
      food_name: 'momos', food_name_hi: 'मोमो',
      aliases: JSON.stringify(['dim sum', 'dumplings', 'veg momos', 'chicken momos', 'मोमो', 'momo']),
      default_unit: 'plate', default_quantity: 1,
      calories_per_serving: 250, protein_per_serving: 10, carbs_per_serving: 30, fat_per_serving: 10,
      fibre_per_serving: 2.0, sugar_per_serving: 2.0, sodium_per_serving: 500,
      category: 'snack', is_veg: false, confidence: 0.94,
    },
    {
      food_name: 'pakora', food_name_hi: 'पकोड़ा',
      aliases: JSON.stringify(['pakode', 'bhajiya', 'bhaji', 'fritters', 'पकोड़ा', 'pakoda', 'bhajiyas']),
      default_unit: 'piece', default_quantity: 5,
      calories_per_serving: 200, protein_per_serving: 4.0, carbs_per_serving: 18, fat_per_serving: 13,
      fibre_per_serving: 1.5, sugar_per_serving: 1.0, sodium_per_serving: 300,
      category: 'snack', is_veg: true, confidence: 0.95,
    },
    {
      food_name: 'vada pav', food_name_hi: 'वड़ा पाव',
      aliases: JSON.stringify(['vada paw', 'wada pav', 'batata vada', 'वड़ा पाव', 'vadapav']),
      default_unit: 'piece', default_quantity: 1,
      calories_per_serving: 286, protein_per_serving: 5.0, carbs_per_serving: 36, fat_per_serving: 14,
      fibre_per_serving: 2.0, sugar_per_serving: 2.0, sodium_per_serving: 450,
      category: 'snack', is_veg: true, confidence: 0.95,
    },
    {
      food_name: 'bhel puri', food_name_hi: 'भेल पूरी',
      aliases: JSON.stringify(['bhelpuri', 'bhel', 'झालमुड़ी', 'भेल पूरी', 'jhal muri']),
      default_unit: 'plate', default_quantity: 1,
      calories_per_serving: 180, protein_per_serving: 4.0, carbs_per_serving: 28, fat_per_serving: 6.0,
      fibre_per_serving: 2.0, sugar_per_serving: 3.0, sodium_per_serving: 400,
      category: 'snack', is_veg: true, confidence: 0.95,
    },
    {
      food_name: 'pav bhaji', food_name_hi: 'पाव भाजी',
      aliases: JSON.stringify(['pav bhaji', 'pavbhaji', 'pao bhaji', 'पाव भाजी', 'mumbai pav bhaji']),
      default_unit: 'plate', default_quantity: 1,
      calories_per_serving: 400, protein_per_serving: 10, carbs_per_serving: 50, fat_per_serving: 18,
      fibre_per_serving: 5.0, sugar_per_serving: 5.0, sodium_per_serving: 800,
      category: 'snack', is_veg: true, confidence: 0.95,
    },
    {
      food_name: 'pani puri', food_name_hi: 'पानी पूरी',
      aliases: JSON.stringify(['golgappa', 'gupchup', 'fuchka', 'puchka', 'पानी पूरी', 'gol gappa']),
      default_unit: 'plate', default_quantity: 1,
      calories_per_serving: 180, protein_per_serving: 3.5, carbs_per_serving: 28, fat_per_serving: 6.0,
      fibre_per_serving: 2.0, sugar_per_serving: 2.0, sodium_per_serving: 350,
      category: 'snack', is_veg: true, confidence: 0.95,
    },
    {
      food_name: 'maggi', food_name_hi: 'मैगी',
      aliases: JSON.stringify(['noodles', 'instant noodles', 'maggi noodles', 'मैगी', 'maagi']),
      default_unit: 'plate', default_quantity: 1,
      calories_per_serving: 360, protein_per_serving: 8.0, carbs_per_serving: 48, fat_per_serving: 15,
      fibre_per_serving: 2.0, sugar_per_serving: 1.5, sodium_per_serving: 900,
      category: 'snack', is_veg: true, confidence: 0.96,
    },
    {
      food_name: 'chole bhature', food_name_hi: 'छोले भटूरे',
      aliases: JSON.stringify(['bhatura with chole', 'छोले भटूरे', 'cholebhature', 'bhatura']),
      default_unit: 'plate', default_quantity: 1,
      calories_per_serving: 520, protein_per_serving: 14, carbs_per_serving: 68, fat_per_serving: 22,
      fibre_per_serving: 6.0, sugar_per_serving: 3.0, sodium_per_serving: 900,
      category: 'snack', is_veg: true, confidence: 0.94,
    },

    // ━━━━━━━━━━━━━ SUPPLEMENTS & HEALTH ━━━━━━━━━━━━━
    {
      food_name: 'whey protein', food_name_hi: 'व्हे प्रोटीन',
      aliases: JSON.stringify(['whey', 'protein powder', 'scoop protein', 'whey supplement', 'व्हे प्रोटीन', 'whey liya']),
      default_unit: 'scoop', default_quantity: 1,
      calories_per_serving: 120, protein_per_serving: 24, carbs_per_serving: 3, fat_per_serving: 1.5,
      fibre_per_serving: 0, sugar_per_serving: 1.0, sodium_per_serving: 100,
      category: 'protein', is_veg: true, confidence: 0.96,
    },
    {
      food_name: 'peanut butter', food_name_hi: 'पीनट बटर',
      aliases: JSON.stringify(['pb', 'peanut butter toast', 'moong fali butter', 'पीनट बटर', 'peanut paste']),
      default_unit: 'tablespoon', default_quantity: 1,
      calories_per_serving: 94, protein_per_serving: 4.0, carbs_per_serving: 3.5, fat_per_serving: 8.0,
      fibre_per_serving: 1.0, sugar_per_serving: 1.0, sodium_per_serving: 73,
      category: 'protein', is_veg: true, confidence: 0.97,
    },
    {
      food_name: 'almonds', food_name_hi: 'बादाम',
      aliases: JSON.stringify(['badam', 'soaked almonds', 'बादाम', 'almond nuts']),
      default_unit: 'handful', default_quantity: 10,
      calories_per_serving: 70, protein_per_serving: 2.5, carbs_per_serving: 2.5, fat_per_serving: 6.0,
      fibre_per_serving: 1.2, sugar_per_serving: 0.5, sodium_per_serving: 0,
      category: 'snack', is_veg: true, confidence: 0.97,
    },
    {
      food_name: 'walnuts', food_name_hi: 'अखरोट',
      aliases: JSON.stringify(['akhrot', 'अखरोट', 'walnut']),
      default_unit: 'handful', default_quantity: 1,
      calories_per_serving: 65, protein_per_serving: 1.5, carbs_per_serving: 1.4, fat_per_serving: 6.5,
      fibre_per_serving: 0.7, sugar_per_serving: 0.3, sodium_per_serving: 0,
      category: 'snack', is_veg: true, confidence: 0.97,
    },
    {
      food_name: 'greek yogurt', food_name_hi: 'ग्रीक योगर्ट',
      aliases: JSON.stringify(['hung curd', 'thick curd', 'greek curd', 'ग्रीक योगर्ट', 'chakka']),
      default_unit: 'katori', default_quantity: 1,
      calories_per_serving: 100, protein_per_serving: 10, carbs_per_serving: 6, fat_per_serving: 4.0,
      fibre_per_serving: 0, sugar_per_serving: 4.0, sodium_per_serving: 50,
      category: 'dairy', is_veg: true, confidence: 0.95,
    },

    // ━━━━━━━━━━━━━ SWEETS ━━━━━━━━━━━━━
    {
      food_name: 'gulab jamun', food_name_hi: 'गुलाब जामुन',
      aliases: JSON.stringify(['gulab jamun', 'जामुन', 'गुलाब जामुन']),
      default_unit: 'piece', default_quantity: 1,
      calories_per_serving: 150, protein_per_serving: 2.0, carbs_per_serving: 22, fat_per_serving: 6.0,
      fibre_per_serving: 0.2, sugar_per_serving: 18, sodium_per_serving: 40,
      category: 'sweet', is_veg: true, confidence: 0.96,
    },
    {
      food_name: 'jalebi', food_name_hi: 'जलेबी',
      aliases: JSON.stringify(['jalebi', 'जलेबी', 'imarti']),
      default_unit: 'piece', default_quantity: 1,
      calories_per_serving: 150, protein_per_serving: 1.5, carbs_per_serving: 25, fat_per_serving: 5.5,
      fibre_per_serving: 0.1, sugar_per_serving: 20, sodium_per_serving: 20,
      category: 'sweet', is_veg: true, confidence: 0.96,
    },
    {
      food_name: 'rasgulla', food_name_hi: 'रसगुल्ला',
      aliases: JSON.stringify(['rosogolla', 'rasgolla', 'रसगुल्ला', 'Bengali sweet']),
      default_unit: 'piece', default_quantity: 1,
      calories_per_serving: 125, protein_per_serving: 3.0, carbs_per_serving: 20, fat_per_serving: 4.0,
      fibre_per_serving: 0, sugar_per_serving: 18, sodium_per_serving: 30,
      category: 'sweet', is_veg: true, confidence: 0.96,
    },
    {
      food_name: 'halwa', food_name_hi: 'हलवा',
      aliases: JSON.stringify(['sooji halwa', 'gajar halwa', 'moong dal halwa', 'हलवा', 'sheera']),
      default_unit: 'katori', default_quantity: 1,
      calories_per_serving: 260, protein_per_serving: 4.0, carbs_per_serving: 38, fat_per_serving: 11,
      fibre_per_serving: 1.0, sugar_per_serving: 25, sodium_per_serving: 80,
      category: 'sweet', is_veg: true, confidence: 0.94,
    },
    {
      food_name: 'kheer', food_name_hi: 'खीर',
      aliases: JSON.stringify(['rice kheer', 'payasam', 'payesh', 'खीर', 'phirni']),
      default_unit: 'katori', default_quantity: 1,
      calories_per_serving: 220, protein_per_serving: 5.5, carbs_per_serving: 35, fat_per_serving: 7.0,
      fibre_per_serving: 0.5, sugar_per_serving: 28, sodium_per_serving: 60,
      category: 'sweet', is_veg: true, confidence: 0.95,
    },
    {
      food_name: 'ladoo', food_name_hi: 'लड्डू',
      aliases: JSON.stringify(['laddoo', 'besan ladoo', 'motichoor ladoo', 'लड्डू', 'modak']),
      default_unit: 'piece', default_quantity: 1,
      calories_per_serving: 200, protein_per_serving: 3.5, carbs_per_serving: 28, fat_per_serving: 9.0,
      fibre_per_serving: 1.0, sugar_per_serving: 20, sodium_per_serving: 50,
      category: 'sweet', is_veg: true, confidence: 0.95,
    },

    // ━━━━━━━━━━━━━ FASTING & REGIONAL ━━━━━━━━━━━━━
    {
      food_name: 'sabudana khichdi', food_name_hi: 'साबूदाना खिचड़ी',
      aliases: JSON.stringify(['sago khichdi', 'sabudana', 'vrat food', 'साबूदाना', 'saboodana']),
      default_unit: 'plate', default_quantity: 1,
      calories_per_serving: 340, protein_per_serving: 6.0, carbs_per_serving: 55, fat_per_serving: 12,
      fibre_per_serving: 1.5, sugar_per_serving: 1.0, sodium_per_serving: 300,
      category: 'grain', is_veg: true, confidence: 0.95,
    },
    {
      food_name: 'dhokla', food_name_hi: 'ढोकला',
      aliases: JSON.stringify(['besan dhokla', 'khaman', 'गुजराती ढोकला', 'ढोकला', 'khaman dhokla']),
      default_unit: 'piece', default_quantity: 2,
      calories_per_serving: 160, protein_per_serving: 6.5, carbs_per_serving: 22, fat_per_serving: 5.0,
      fibre_per_serving: 2.0, sugar_per_serving: 3.0, sodium_per_serving: 400,
      category: 'snack', is_veg: true, confidence: 0.95,
    },
    {
      food_name: 'thepla', food_name_hi: 'थेपला',
      aliases: JSON.stringify(['methi thepla', 'gujarati thepla', 'थेपला', 'thelpa']),
      default_unit: 'piece', default_quantity: 1,
      calories_per_serving: 180, protein_per_serving: 4.5, carbs_per_serving: 22, fat_per_serving: 8.0,
      fibre_per_serving: 2.5, sugar_per_serving: 1.0, sodium_per_serving: 200,
      category: 'grain', is_veg: true, confidence: 0.94,
    },
    {
      food_name: 'idli sambar', food_name_hi: 'इडली सांभर',
      aliases: JSON.stringify(['idli with sambar', 'south indian breakfast', 'इडली सांभर', 'idly sambar']),
      default_unit: 'plate', default_quantity: 1,
      calories_per_serving: 280, protein_per_serving: 11, carbs_per_serving: 44, fat_per_serving: 6.5,
      fibre_per_serving: 5.0, sugar_per_serving: 3.0, sodium_per_serving: 600,
      category: 'grain', is_veg: true, confidence: 0.95,
    },

    // ━━━━━━━━━━━━━ CONDIMENTS & EXTRAS ━━━━━━━━━━━━━
    {
      food_name: 'ghee', food_name_hi: 'घी',
      aliases: JSON.stringify(['clarified butter', 'desi ghee', 'cow ghee', 'घी']),
      default_unit: 'tablespoon', default_quantity: 1,
      calories_per_serving: 112, protein_per_serving: 0, carbs_per_serving: 0, fat_per_serving: 12.7,
      fibre_per_serving: 0, sugar_per_serving: 0, sodium_per_serving: 0,
      category: 'dairy', is_veg: true, confidence: 0.98,
    },
    {
      food_name: 'butter', food_name_hi: 'मक्खन',
      aliases: JSON.stringify(['makhan', 'amul butter', 'white butter', 'मक्खन']),
      default_unit: 'tablespoon', default_quantity: 1,
      calories_per_serving: 102, protein_per_serving: 0.1, carbs_per_serving: 0, fat_per_serving: 11.5,
      fibre_per_serving: 0, sugar_per_serving: 0, sodium_per_serving: 82,
      category: 'dairy', is_veg: true, confidence: 0.97,
    },
    {
      food_name: 'pickle', food_name_hi: 'अचार',
      aliases: JSON.stringify(['achar', 'mango pickle', 'nimbu achar', 'अचार', 'acchar']),
      default_unit: 'tablespoon', default_quantity: 1,
      calories_per_serving: 25, protein_per_serving: 0.3, carbs_per_serving: 2.0, fat_per_serving: 2.0,
      fibre_per_serving: 0.5, sugar_per_serving: 0.5, sodium_per_serving: 400,
      category: 'snack', is_veg: true, confidence: 0.94,
    },
    {
      food_name: 'papad', food_name_hi: 'पापड़',
      aliases: JSON.stringify(['papadum', 'appalam', 'pappad', 'पापड़']),
      default_unit: 'piece', default_quantity: 1,
      calories_per_serving: 50, protein_per_serving: 2.5, carbs_per_serving: 7, fat_per_serving: 1.5,
      fibre_per_serving: 1.0, sugar_per_serving: 0.2, sodium_per_serving: 400,
      category: 'snack', is_veg: true, confidence: 0.96,
    },
    {
      food_name: 'coconut chutney', food_name_hi: 'नारियल की चटनी',
      aliases: JSON.stringify(['nariyal chutney', 'white chutney', 'नारियल की चटनी']),
      default_unit: 'tablespoon', default_quantity: 2,
      calories_per_serving: 60, protein_per_serving: 1.0, carbs_per_serving: 3.5, fat_per_serving: 5.0,
      fibre_per_serving: 1.5, sugar_per_serving: 1.0, sodium_per_serving: 120,
      category: 'snack', is_veg: true, confidence: 0.95,
    },

    // ━━━━━━━━━━━━━ COMBO / THALI DISHES ━━━━━━━━━━━━━
    {
      food_name: 'dal chawal', food_name_hi: 'दाल चावल',
      aliases: JSON.stringify(['dal rice', 'rice dal', 'दाल चावल', 'daal chawal', 'lentil rice']),
      default_unit: 'plate', default_quantity: 1,
      calories_per_serving: 380, protein_per_serving: 12, carbs_per_serving: 60, fat_per_serving: 8.0,
      fibre_per_serving: 5.0, sugar_per_serving: 1.5, sodium_per_serving: 500,
      category: 'grain', is_veg: true, confidence: 0.95,
    },
    {
      food_name: 'rajma chawal', food_name_hi: 'राजमा चावल',
      aliases: JSON.stringify(['rajma rice', 'राजमा चावल', 'kidney bean rice']),
      default_unit: 'plate', default_quantity: 1,
      calories_per_serving: 420, protein_per_serving: 15, carbs_per_serving: 65, fat_per_serving: 9.0,
      fibre_per_serving: 7.0, sugar_per_serving: 2.0, sodium_per_serving: 550,
      category: 'grain', is_veg: true, confidence: 0.95,
    },
    {
      food_name: 'chole chawal', food_name_hi: 'छोले चावल',
      aliases: JSON.stringify(['chana rice', 'छोले चावल', 'chickpea rice']),
      default_unit: 'plate', default_quantity: 1,
      calories_per_serving: 440, protein_per_serving: 14, carbs_per_serving: 68, fat_per_serving: 10,
      fibre_per_serving: 7.0, sugar_per_serving: 2.5, sodium_per_serving: 600,
      category: 'grain', is_veg: true, confidence: 0.94,
    },
    {
      food_name: 'roti sabzi', food_name_hi: 'रोटी सब्जी',
      aliases: JSON.stringify(['chapati sabzi', 'roti vegetable', 'रोटी सब्जी', 'dal roti', 'sabzi roti']),
      default_unit: 'plate', default_quantity: 1,
      calories_per_serving: 350, protein_per_serving: 9.0, carbs_per_serving: 45, fat_per_serving: 14,
      fibre_per_serving: 6.0, sugar_per_serving: 3.0, sodium_per_serving: 650,
      category: 'grain', is_veg: true, confidence: 0.93,
    },
  ];

  return knex('indian_food_cache').insert(foods);
}
